### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by josselex** [sestei/coatingtk#16]
Hi,
I tried to install this but it fails with this error:

python setup.py install

```
running install
running build
running build_exe
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    executables = executables)
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\cx_Freeze\dist.py", line 362, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\distutils\command\install.py", line 563, in run
    self.run_command('build')
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\cx_Freeze\dist.py", line 232, in run
    freezer.Freeze()
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\cx_Freeze\freezer.py", line 619, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\cx_Freeze\freezer.py", line 376, in _GetModuleFinder
    finder.IncludeModule(name)
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\cx_Freeze\finder.py", line 678, in IncludeModule
    namespace = namespace)
  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\cx_Freeze\finder.py", line 386, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'gui.plots.plot_R_angle'
```

**Comment by sestei** [comment]
Hi,
sorry, I never actually tried/supported the setup.py installation routine. I should probably implement this soon. Can you try first of all whether it works when you just clone everything and then run the CoatingGUI.py file? This should ideally start the GUI application, however it will require quite a few dependencies, such as PyQt4, numpy, ...

**Comment by sestei** [comment]
No further response received, closing for now.

**Comment by josselex** [comment]
I get the same error. Somehow this import thing does not work.
Tested on python 2.7.10 (and python 3 after translation with 2to3).

```
  File "<ipython-input-1-12b046e72e94>", line 1, in <module>
    runfile('C:/Users/q/Dropbox/Cavity/python/anderes/dielectric/CoatingGUI.py', wdir='C:/Users/q/Dropbox/Cavity/python/anderes/dielectric')

  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/q/Dropbox/Cavity/python/anderes/dielectric/CoatingGUI.py", line 17, in <module>
    Window = MainWindow(vars(args))

  File "gui\mainWindow.py", line 49, in __init__
    self.plots = plothandler.collect_plots()

  File "gui\plothandler.py", line 16, in collect_plots
    m = import_module('gui.plots.'+mod)

  File "C:\Users\q\Downloads\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)

ImportError: No module named plot_R_angle


```

**Comment by sestei** [comment]
Ok, I'll look into this again, but might not be able to do this before the weekend.

**Comment by sestei** [comment]
Hm... can you have a look into the `gui/plots` directory please? There should be a file named `ui_plotR_Angle.ui` and a file named `plot_R_Angle.py`. Can you please confirm they are there, and have the correct upper/lowercase spelling (in your error message, it says `plot_R_angle` with a lowercase `a`...)

**Comment by sestei** [comment]
Eh... just checked here on github. Indeed, the name of that file is wrong. Apparently a change in lower/uppercase has not been picked up correctly. I'll fix this, can you then retry with a new, clean copy of the repository, please? (Or just rename `ui_plotR_angle.ui` to `ui_plotR_Angle.ui` and also `ui_plotR_Lambda.ui` instead of `ui_plotR_lambda.ui`)

**Comment by josselex** [comment]
Yes! Now it works!
I had to fix one minor bug. I will submit this as a pull request.
